name: {{#snakeCase}}{{name}}{{/snakeCase}}
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  cloud_firestore: ^3.4.1
  cloud_functions: ^3.3.3
  firebase_auth: ^3.5.1
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

  flutter_lints: ^2.0.0
  lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
flutter_intl:
  enabled: true
