// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7-U7E2lM56s4avAYndCRn88LM7T1ACLY',
    appId: '1:468460293019:web:f8edb8d0f16c177836ef3e',
    messagingSenderId: '468460293019',
    projectId: 'new-flutter-template',
    authDomain: 'new-flutter-template.firebaseapp.com',
    storageBucket: 'new-flutter-template.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbdQBVG1vJDacn0IE-EA0AgOa-U83c0e8',
    appId: '1:468460293019:android:6f542c2ec4979bf436ef3e',
    messagingSenderId: '468460293019',
    projectId: 'new-flutter-template',
    storageBucket: 'new-flutter-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6KIwtowrOS2JWjwcp3Yv-y6cBTGzpHyY',
    appId: '1:468460293019:ios:d492f3db7ec45cb436ef3e',
    messagingSenderId: '468460293019',
    projectId: 'new-flutter-template',
    storageBucket: 'new-flutter-template.appspot.com',
    iosClientId: '468460293019-7tkj0dg6ke4m9jqtsenr842ocuia4sa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6KIwtowrOS2JWjwcp3Yv-y6cBTGzpHyY',
    appId: '1:468460293019:ios:d492f3db7ec45cb436ef3e',
    messagingSenderId: '468460293019',
    projectId: 'new-flutter-template',
    storageBucket: 'new-flutter-template.appspot.com',
    iosClientId: '468460293019-7tkj0dg6ke4m9jqtsenr842ocuia4sa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutterTemplate',
  );
}
